name: Angular Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
    steps:
    - uses: actions/checkout@v4
    - name: Build the Angular Application Docker image
      run: docker build . --file docker/Dockerfile --tag frontend:${{ env.git_hash }}
      working-directory: ${{ env.working-directory}}
