---
name: Angular Linting

on:
  workflow_run:
    workflows: [Angular Testing]
    types: [completed]

jobs:
    angular-lint:
      name: Angular Lint
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
      steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Code Linter
        run: yarn lint

      - name: Run Style Linter
        run: yarn lint:style