name: Angular Linting

on:
  workflow_call:
    inputs:
      node_versions:
        description: 'Comma-separated list of node versions'
        required: true
        type: string

jobs:
  angular-lint:
    name: Angular Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{fromJson(inputs.node_versions)}}
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Linting Code
      run: npm run lint
      
    - name: Linting Styling
      run: npm run lint:style