name: Angular Linting

on:
  workflow_call:
    inputs:
      node_versions:
        required: true
        type: string

jobs:
  angular-lint:
    name: Angular Lint
    runs-on: ubuntu-latest
    permissions: read-all
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_versions }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Linting Code
      run: npm run lint
      
    - name: Linting Styling
      run: npm run lint:style