---
name: Building
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  codeql-security-scan:
    uses: ./.github/workflows/codeql.yml
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    with:
      languages: "java-kotlin,javascript-typescript"
  
  sonarcloud-security-scan:
    uses: ./.github/workflows/sonarcloud.yml
    with:
      java_version: 21

  testing-java:
    needs: [codeql-security-scan]
    if: success()
    uses: ./.github/workflows/gradle-testing.yml
    with:
      java_version: 21
  
  testing-angular:
    needs: [codeql-security-scan]
    if: success()
    uses: ./.github/workflows/angular-testing.yml
    with:
      node_versions: "22.x"

  linting-angular:
    needs: [testing-angular]
    if: success()
    uses: ./.github/workflows/angular-linting.yml
    with:
      node_versions: "22.x"

  build-angular-docker-image:
    needs: [linting-angular]
    if: success()
    uses: ./.github/workflows/angular-docker-image.yml

  build-java-api-docker-image:
    needs: [testing-java]
    if: success()
    uses: ./.github/workflows/java-rest-api-docker-image.yml

  # deploy-dev:
  #   needs: [build-angular-docker-image, build-java-api-docker-image]
  #   uses: ./.github/workflows/deploy-dev.yml