name: Java Rest API Docker Image CI
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Build the Java Rest API Docker image
      run: docker build . --file docker/Dockerfile --tag backend:${{ env.git_hash }}
